### ISSUE TITLE
ModuleNotFoundError: No module named 'dream'

### ISSUE THREAD

**Issue by zerosix** [robobeebop/VQGAN-CLIP-Video#1]
![screenshot](https://user-images.githubusercontent.com/3020036/149608033-9b043dbe-1027-40dc-b739-911adb46b61a.png)

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-29-f5b7b9bd19d4> in <module>()
      1 # @title Select a model to load
----> 2 from dream import Dream
      3 from os.path import exists
      4 get_ipython().system('mkdir checkpoints')
      5 ckpt_dir = "/content/checkpoints/"

ModuleNotFoundError: No module named 'dream'

**Comment by robobeebop** [comment]
I believe this was a cloning issue from notebook itself, should work properly now.
