### ISSUE TITLE
TypeError: deepdream() got multiple values for argument 'iter_n'

### ISSUE THREAD

**Issue by basemdabbour** [robobeebop/VQGAN-CLIP-Video#2]
Hey i got this error inside Dream code. 
i think the following argument should change :

frame = None
if do_wait_first_frame:
    frame = dream.deepdream(np_img, text_prompts, (x, y), iter_n=iter_n, step_size=step_size, init_weight=frame_weight)
else:
    frame = dream.deepdream(np_img, text_prompts, (x, y), iter_n=wait_iter_n, step_size=step_size, init_weight=frame_weight)

**Comment by robobeebop** [comment]
Fixed it.
